language: python

python:
    - "3.6"

install:
    - pip3 install .
    - pip3 install -r dev-requirements.txt

script:
    - pytest-3 test_resolveDnsRecordsFromFile.py  
after_success:
    - coveralls
