language: python

python:
    - "3.5.3"

install:
    - pip install -r dev-requirements.txt
    - pip install -r requirements.txt
script:
    - pytest test_resolveDnsRecordsFromFile.py 
    - python test_resolveDnsRecordsFromFile.py 
after_success:
    - coveralls
