language: python

python:
    - "3.5.3"

install:
    - pip install -r dev-requirements.txt

script:
    - py.test resolveDnsRecordsFromFile.py 
    - python test_resolveDnsRecordsFromFile.py 
after_success:
    - coveralls
